steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'server'
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bug-hunt-backend', '.']
    dir: 'server'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bug-hunt-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'bug-hunt-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/bug-hunt-backend'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8081'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--http-health-check-path'
    - '/health'

images:
  - 'gcr.io/$PROJECT_ID/bug-hunt-backend'

timeout: '1200s'