steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bug-hunt-backend', '.']
    dir: 'server'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bug-hunt-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'bug-hunt-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/bug-hunt-backend'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--http-health-check-path'
    - '/health'
    - '--set-secrets'
    - 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest,EMAIL_USER=EMAIL_USER:latest,EMAIL_PASS=EMAIL_PASS:latest,ADMIN_EMAIL=ADMIN_EMAIL:latest'
    - '--set-env-vars'
    - 'NODE_ENV=production,ALLOWED_ORIGINS=https://your-app-name.vercel.app,https://your-app-name-git-main.vercel.app'

images:
  - 'gcr.io/$PROJECT_ID/bug-hunt-backend'

timeout: '1200s'